# deployment parameters (used for model freezing/onnx export)

batch_size: 1
input_channels: 4
input_height: 322
input_width: 432

target_height: 322
target_width: 432

keypoint_radius: 15 # in target pixels
