# deployment parameters (only used for model onnx/pt export)

batch_size: 1
input_channels: 4
input_height: 966
input_width: 1296

target_height: 322
target_width: 432

keypoint_radius: 15 # in target pixels
