rotate: True
flip_x: True
flip_y: True

scale_min: 0.8
scale_max: 1.2

shear_min: -0.2
shear_max: 0.2

translation_min: -50.0
translation_max: 50.0

brightness_min: -0.2
brightness_max: 0.2

saturation_min: -0.2
saturation_max: 0.2

contrast_min: 0.2
contrast_max: -0.2

blur_min: 0.0
blur_max: 3.0

noise_min: 0.0
noise_max: 0.2
