rotate: True
flip_x: True
flip_y: True

scale_min: 0.8
scale_max: 1.2

shear_min: -0.2
shear_max: 0.2

translation_min: -300.0
translation_max: 300.0

brightness_min: -0.05
brightness_max: 0.05

saturation_min: -0.05
saturation_max: 0.05

contrast_min: 0.05
contrast_max: -0.05

blur_min: 0.0
blur_max: 1.0

noise_min: 0.0
noise_max: 0.0
