in_channels: 4
num_filters_encoder: [32, 64, 128]
num_filters_semantic_decoder: [64, 32]
num_filters_stem_decoder: [64, 32]
num_conv_encoder: [2, 2, 2]
num_conv_semantic_decoder: [2, 2]
num_conv_stem_decoder: [2, 2]
dropout_rate: 0.2
