label_background: 0
label_ignore: 1
label_weed: 20001
label_sugar_beet: 10000

input_height: 322
input_width: 432

target_height: 322
target_width: 432

# normalization parameters
mean_rgb: [0.3855186419211486, 0.22667925089614235, 0.053568861512275835]
mean_nir: 0.22021524472007756
std_rgb: [0.12405956089564812, 0.07152223154313433, 0.010760791977355064]
std_nir: 0.06568905699414836

path_to_rgb_images: 'sugar_beet_dataset/images/rgb/'
suffix_rgb_images: '.png'

path_to_nir_images: 'sugar_beet_dataset/images/nir/'
suffix_nir_images: '.png'

path_to_semantic_labels: 'sugar_beet_dataset/annotations/PNG/pixelwise/iMap/'
suffix_semantic_labels: '_GroundTruth_iMap.png'

path_to_yaml_annotations: 'sugar_beet_dataset/annotations/YAML/'
suffix_yaml_annotations: '.yaml'

# seed for random transformation of train split
seed: 0
