# training parameters

batch_size: 3
input_channels: 4
input_height: 322
input_width: 432

target_height: 322
target_width: 432

keypoint_radius: 15 # in target pixels

learning_rate: 0.001
num_epochs: 500

# weighting of losses
semantic_loss_weight: 0.3
stem_loss_weight: 0.7
stem_classification_loss_weight: 0.05
stem_regression_loss_weight: 0.95

# class weights for semantic segmentation
weight_background: 0.05
weight_weed: 0.8
weight_sugar_beet: 0.15

# class weights for stem keypoint detection
weight_stem_background: 0.1
weight_stem: 0.9

size_test_set: 50

architecture_name: 'simple_unet' # 'fcn', 'simple_unet'
path_to_weights_file: 'simple_unet.pth'

stem_inference_device_option: 'cuda' # 'cuda' (= CUDA), 'cpu' (= Pytorch C++ API), 'naive' (= numpy)
stem_inference_threshold: 0.01 # pixel with a keypoint confidence below this value do not cast votes at all
