keypoint_radius: 15 # in target pixels

learning_rate: 0.001
num_epochs: 500

# weighting of losses
semantic_loss_weight: 10.0
stem_loss_weight: 1.0
stem_classification_loss_weight: 1.0
stem_regression_loss_weight: 1.0

# class weights for semantic segmentation
weight_background: 1.0
weight_weed: 20.0
weight_sugar_beet: 5.0

# class weights for stem keypoint detection
weight_stem_background: 1.0
weight_stem: 10.0

# weight semantic loss depending on object size
# used to balance between small and large plants
size_depedent_weight: False

# set thresholds specific for architecture and checkpoint in separate config file
# sugar_beet_threshold: 0.0 # confidence threshold to be assigned to this class
# weed_threshold: 0.0 # sugar beets treated with priority for thresholds <= 0.5

stem_inference_threshold_votes: 0.001 # pixel with a keypoint confidence below this value do not cast votes at all
stem_inference_kernel_size_votes: 3 # pixels also vote for neighbors within this window, should be odd
stem_inference_kernel_size_peaks: 5 # non-maximum suppression for all peaks in this window, should be odd
stem_inference_threshold_peaks: 0.001 # only return stems with a score large than this value (a further threshold can be applied for evaluation)

# set thresholds specific for architecture and checkpoint in separate config file
# stem_score_threshold: 0.0

# evaluation
tolerance_radius: 5.0 # in target pixels
