keypoint_radius: 15 # in target pixels

learning_rate: 0.001
num_epochs: 500

# weighting of losses
semantic_loss_weight: 10.0
stem_loss_weight: 1.0
stem_classification_loss_weight: 1.0
stem_regression_loss_weight: 1.0

# class weights for semantic segmentation
weight_background: 1.0
weight_weed: 10.0
weight_sugar_beet: 10.0

# class weights for stem keypoint detection
weight_stem_background: 1.0
weight_stem: 10.0

stem_inference_device_option: 'pytorch' # 'cuda' (= CUDA), 'cpu' (= Pytorch C++ API), 'pytorch' (= pytorch index_put)
stem_inference_threshold_votes: 0.001 # pixel with a keypoint confidence below this value do not cast votes at all
stem_inference_threshold_peaks: 0.1 # only pixels with accumulated votes larger than this value are considered as stems
stem_inference_kernel_size_votes: 5 # pixels also vote for neighbors within this window, should be odd
stem_inference_kernel_size_peaks: 9 # non-maximum suppression for all peaks in this window, should be odd

# evaluation
tolerance_radius: 5.0 # in target pixels
